### ISSUE TITLE
Spacing on side navigation links

### ISSUE THREAD

**Issue by tOmoness** [mixradio/apidocs#1]
Not a huge issue. Was just bugging me.

The hover effect on the side navigation links shows the text tucked right up to the left hand side. Adding: `#sidebar > li > a { padding: 10px 15px; }` just makes it a little less squished.

Before:
![image](https://cloud.githubusercontent.com/assets/4624841/7346747/5d7e4514-ecd9-11e4-9ceb-e30fe5d38304.png)

After:
![image](https://cloud.githubusercontent.com/assets/4624841/7346739/4cc88b44-ecd9-11e4-8db9-cb14a0ffb372.png)

**Comment by srgb** [comment]
Thanks @tOmoness! I have made this change, but have a network issue with the build server, so it won't get deployed  for a few days.

**Comment by srgb** [comment]
This has now been deployed, thanks again
