### ISSUE TITLE
New releases page contains broken information

### ISSUE THREAD

**Issue by MatthewBooth** [mixradio/apidocs#2]
The new releases page contains some information that returns 404's even with proper input

```
http://api.mixrad.io/1.x/gb/products/new/artist/?domain=music&client_id=eac56b8ec397c8a40a4c66ce703a70c5
```

This should return the new releases for the UK, but instead returns a 404 page.

**Comment by srgb** [comment]
Hi Matt, could you let me know which doc page you're looking at please? On the [new releases doc page](http://dev.mixrad.io/doc/rest/public/NewReleases.html), we have a note that the `category` can only be one of `album`, `single` and `track`, so the URL you have should be http://api.mixrad.io/1.x/gb/products/new/album/?domain=music&client_id=eac56b8ec397c8a40a4c66ce703a70c5 for example. 
Sorry if I've missed something.
Cheers,
Steve

**Comment by MatthewBooth** [comment]
Hi Steve,

Well, don't I feel daft now :( That was most definitely it, thanks for the swift reply!

Although, quick question. Do you know anyone working on the MixRadio mobile app that's in development? I have some questions that relate to some images we're developing for you (I work for Bolser, we developed the website) that someone in the development team could help massively and save some guess work on this end!

**Comment by srgb** [comment]
Cool. On the question, of course - can you email the question through Olly please?
